theme: minima
title: DeFiResearchers Blog
author: DeFiResearcher
email: defiresearchers@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A library of free resources that helped me start trading and investing in cryptocurrencies.

# social links
twitter_username: ResearcherDefi # DO NOT include the @ character, or else the build will fail!
github_username:  defiresearchers # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

